config/routes.rb
Rails.application.routes.draw do
  
	root "welcome#index"

	resources :chats
	resources :messages

	namespace :api, defaults: {format: :json} do
		resources :chats
		resources :messages
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chat
end

app/controllers/api/api_controller.rb
class API::APIController < ActionController::Base
end

app/controllers/api/chats_controller.rb
class API::ChatsController < API::APIController

	def index
		render json: Chat.all
	end

	def show
		@chat = Chat.find params[:id]
		render json: @chat, include: :messages
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

	def show
		@chat = Chat.find params[:id]
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@chats = Chat.all.reverse
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/show.html.erb
<section ng-controller='ChatShow as vm'>
	<h1><%= @chat.title %></h1>

	<p ng-repeat="message in vm.chat.messages">
		<b>{{message.user}}: </b>{{message.content}}
	</p>

	<form>
		Nome: <input type="text" ng-model="vm.message.user">
		Mensagem: <input type="text" ng-model="vm.message.content">
		<button ng-click="vm.submit()">Enviar</button>

		{{vm.message}}
	</form>

	<br><br><br><br>
	{{vm.messages}}


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app="app">
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<section ng-controller='ChatIndex as vm'>

	<h1>CHATs Disponiveis</h1>

	<% @chats.each do |c| %>
		<p>
			<%= link_to c.title, chat_path(c.id) %>
		</p>
	<% end %>

</section>